version: '3.8'
services:
  react-app:
    build:
      context: ./lottery-front
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
  express-app:
    build:
      context: ./lottery-back
      dockerfile: Dockerfile
    ports:
      - "3009:3009"


   
  